### ISSUE TITLE
The data is stale

### ISSUE THREAD

**Issue by 0xR** [davideast/hnpwa-api#12]
Many hnpwa apps now have stale data. For example look at this endpoint https://api.hnpwa.com/v0/news/1.json

The top story is 7 days old https://news.ycombinator.com/item?id=18295585

**Comment by davideast** [comment]
Should be fixed! It was a dependency mismatch with the Firebase CLI. Should be working now. 

See https://github.com/tastejs/hacker-news-pwas/pull/168.
