### ISSUE TITLE
https://api.hnpwa.com/v0/jobs/1.json blocked by CORS policy

### ISSUE THREAD

**Issue by Rich-Harris** [davideast/hnpwa-api#15]
Hey — I'm seeing this error when I try to navigate to the jobs tab on an HN implementation that uses this API:

<img width="713" alt="Screen Shot 2020-05-15 at 22 30 25" src="https://user-images.githubusercontent.com/1162160/82108323-b7a19880-96fb-11ea-9dae-794dce039d72.png">

It seems to be specific to the `/jobs` endpoint. Any ideas? Thanks!

**Comment by Rich-Harris** [comment]
This seems to be fixed now — closing

**Comment by davideast** [comment]
Sorry, had fixed this and forgot to comment. Please open again if it comes back up. CORS 🤦
