### ISSUE TITLE
FireStore option?

### ISSUE THREAD

**Issue by tycho01** [davideast/hnpwa-api#3]
WIth the recent announcement of [FireStore](https://news.ycombinator.com/item?id=15393396), I think it'd be interesting if HNPWA implementations could use that as an alternative to Firebase. I guess this would probably be the most logical place to start for that. Might you be open to the idea?

**Comment by davideast** [comment]
This API is meant to be used in a REST only context. The backing is with the Realtime Database and until HN switches to Firestore we're left with either REST or RTDB.
